### ISSUE TITLE
3.0/new-routing-8 fails to compile because the Static folder is missing

### ISSUE THREAD

**Issue by AlexisAuriac** [dodyg/practical-aspnetcore#223]
When I tried to compile 3.0/new-routing-8 it failed with an error about the Static folder being missing.
Renaming the static folder to Static fixed it.

**Comment by dodyg** [comment]
Can you please elaborate because I can't replicate the problem on both versions.

https://github.com/dodyg/practical-aspnetcore/tree/master/projects/3-0/new-routing-8
![old-routing](https://user-images.githubusercontent.com/1761249/81267272-7c8dce00-9046-11ea-8919-513f6096dbbf.png)

https://github.com/dodyg/practical-aspnetcore/tree/3.1-LTS/projects/endpoint-routing/new-routing-8
![3-new-routing-8](https://user-images.githubusercontent.com/1761249/81267219-63851d00-9046-11ea-9ae3-ec34065d7baf.png)

**Comment by AlexisAuriac** [comment]
When I try to run ```dotnet run``` on new-routing-8 (both versions) I get this exception:
```
System.IO.DirectoryNotFoundException: /home/alexis/practical-aspnetcore/projects/3-0/new-routing-8/Static/
```
After renaming the ```static/``` folder to ```Static/``` it works correctly.
![error_new-routing-8](https://user-images.githubusercontent.com/39840011/81294558-5cbed000-906f-11ea-97b2-cd0901c1036e.png)

**Comment by dodyg** [comment]
Ah got it. It's the case sensitive name path in Linux. Thanks. I'll fix that.

**Comment by dodyg** [comment]
https://github.com/dodyg/practical-aspnetcore/commit/38b426ce8299b26d778ec6b1892bd259a8182bc3

https://github.com/dodyg/practical-aspnetcore/commit/ddd70da3d5f6b3a43864e4afeea207b6d53a0980
