### ISSUE TITLE
Add sample for gRPC HTTP

### ISSUE THREAD

**Issue by dodyg** [dodyg/practical-aspnetcore#330]
https://github.com/aspnet/AspLabs/tree/main/src/GrpcHttpApi

**Comment by bcr** [comment]
Do you want a port of the existing `grpc` samples to a new folder `grpc-aspnet` using the new API?

**Comment by dodyg** [comment]
Can you please elaborate more about the new APIs? 

- All gRPC samples are already on Minimal APIs https://github.com/dodyg/practical-aspnetcore/tree/net6.0/projects/grpc. 
- All new features for gRPC available on .NET7 is available at https://github.com/dodyg/practical-aspnetcore/tree/net6.0/projects/.net7.

**Comment by bcr** [comment]
1. You said https://github.com/aspnet/AspLabs/tree/main/src/GrpcHttpApi with the title "Add sample for gRPC HTTP"
2. I interpreted that to mean "please create a sample that uses the API that is documented at this location"
3. I saw on the main branch that there is already a set of GRPC examples, but those do not use the API that is documented at the provided URL
4. My offer was to port those examples

If this issue is already under control on another branch that isn't referenced by this issue, my mistake.

**Comment by dodyg** [comment]
Ah thanks for the clarification. Those referenced APIs are already implemented here (5 samples) https://github.com/dodyg/practical-aspnetcore/tree/net6.0/projects/.net7#grpc.

It's my fault for not closing this case.

**Comment by bcr** [comment]
No problem -- I'm doing some hacktoberfest contributions, so I was looking at the issues in your repo.

**Comment by dodyg** [comment]
We need help for samples in SignalR (https://github.com/dodyg/practical-aspnetcore/tree/net6.0/projects/signalr) and Razor Pages https://github.com/dodyg/practical-aspnetcore/tree/net6.0/projects/razor-pages. Those two areas are barely covered.
